// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameApi.proto

package model;

public final class GameApiProtos {
  private GameApiProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateGameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.CreateGameResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .model.Game game = 1;</code>
     */
    boolean hasGame();
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    model.GameProtos.Game getGame();
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    model.GameProtos.GameOrBuilder getGameOrBuilder();

    /**
     * <code>optional string host = 2;</code>
     */
    boolean hasHost();
    /**
     * <code>optional string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <code>optional string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>optional int32 port = 3;</code>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 3;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code model.CreateGameResponse}
   */
  public  static final class CreateGameResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.CreateGameResponse)
      CreateGameResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateGameResponse.newBuilder() to construct.
    private CreateGameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateGameResponse() {
      host_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateGameResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              model.GameProtos.Game.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = game_.toBuilder();
              }
              game_ = input.readMessage(model.GameProtos.Game.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(game_);
                game_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              host_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.GameApiProtos.internal_static_model_CreateGameResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.GameApiProtos.internal_static_model_CreateGameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.GameApiProtos.CreateGameResponse.class, model.GameApiProtos.CreateGameResponse.Builder.class);
    }

    private int bitField0_;
    public static final int GAME_FIELD_NUMBER = 1;
    private model.GameProtos.Game game_;
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    public boolean hasGame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    public model.GameProtos.Game getGame() {
      return game_ == null ? model.GameProtos.Game.getDefaultInstance() : game_;
    }
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    public model.GameProtos.GameOrBuilder getGameOrBuilder() {
      return game_ == null ? model.GameProtos.Game.getDefaultInstance() : game_;
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <code>optional string host = 2;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>optional int32 port = 3;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasGame()) {
        if (!getGame().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getGame());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, port_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGame());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.GameApiProtos.CreateGameResponse)) {
        return super.equals(obj);
      }
      model.GameApiProtos.CreateGameResponse other = (model.GameApiProtos.CreateGameResponse) obj;

      boolean result = true;
      result = result && (hasGame() == other.hasGame());
      if (hasGame()) {
        result = result && getGame()
            .equals(other.getGame());
      }
      result = result && (hasHost() == other.hasHost());
      if (hasHost()) {
        result = result && getHost()
            .equals(other.getHost());
      }
      result = result && (hasPort() == other.hasPort());
      if (hasPort()) {
        result = result && (getPort()
            == other.getPort());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGame()) {
        hash = (37 * hash) + GAME_FIELD_NUMBER;
        hash = (53 * hash) + getGame().hashCode();
      }
      if (hasHost()) {
        hash = (37 * hash) + HOST_FIELD_NUMBER;
        hash = (53 * hash) + getHost().hashCode();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.GameApiProtos.CreateGameResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.CreateGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.CreateGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.CreateGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.GameApiProtos.CreateGameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.CreateGameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.CreateGameResponse)
        model.GameApiProtos.CreateGameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.GameApiProtos.internal_static_model_CreateGameResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.GameApiProtos.internal_static_model_CreateGameResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.GameApiProtos.CreateGameResponse.class, model.GameApiProtos.CreateGameResponse.Builder.class);
      }

      // Construct using model.GameApiProtos.CreateGameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGameFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (gameBuilder_ == null) {
          game_ = null;
        } else {
          gameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.GameApiProtos.internal_static_model_CreateGameResponse_descriptor;
      }

      public model.GameApiProtos.CreateGameResponse getDefaultInstanceForType() {
        return model.GameApiProtos.CreateGameResponse.getDefaultInstance();
      }

      public model.GameApiProtos.CreateGameResponse build() {
        model.GameApiProtos.CreateGameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.GameApiProtos.CreateGameResponse buildPartial() {
        model.GameApiProtos.CreateGameResponse result = new model.GameApiProtos.CreateGameResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (gameBuilder_ == null) {
          result.game_ = game_;
        } else {
          result.game_ = gameBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.GameApiProtos.CreateGameResponse) {
          return mergeFrom((model.GameApiProtos.CreateGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.GameApiProtos.CreateGameResponse other) {
        if (other == model.GameApiProtos.CreateGameResponse.getDefaultInstance()) return this;
        if (other.hasGame()) {
          mergeGame(other.getGame());
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000002;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasGame()) {
          if (!getGame().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.GameApiProtos.CreateGameResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.GameApiProtos.CreateGameResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private model.GameProtos.Game game_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          model.GameProtos.Game, model.GameProtos.Game.Builder, model.GameProtos.GameOrBuilder> gameBuilder_;
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public boolean hasGame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public model.GameProtos.Game getGame() {
        if (gameBuilder_ == null) {
          return game_ == null ? model.GameProtos.Game.getDefaultInstance() : game_;
        } else {
          return gameBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder setGame(model.GameProtos.Game value) {
        if (gameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          game_ = value;
          onChanged();
        } else {
          gameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder setGame(
          model.GameProtos.Game.Builder builderForValue) {
        if (gameBuilder_ == null) {
          game_ = builderForValue.build();
          onChanged();
        } else {
          gameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder mergeGame(model.GameProtos.Game value) {
        if (gameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              game_ != null &&
              game_ != model.GameProtos.Game.getDefaultInstance()) {
            game_ =
              model.GameProtos.Game.newBuilder(game_).mergeFrom(value).buildPartial();
          } else {
            game_ = value;
          }
          onChanged();
        } else {
          gameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder clearGame() {
        if (gameBuilder_ == null) {
          game_ = null;
          onChanged();
        } else {
          gameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public model.GameProtos.Game.Builder getGameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getGameFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public model.GameProtos.GameOrBuilder getGameOrBuilder() {
        if (gameBuilder_ != null) {
          return gameBuilder_.getMessageOrBuilder();
        } else {
          return game_ == null ?
              model.GameProtos.Game.getDefaultInstance() : game_;
        }
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          model.GameProtos.Game, model.GameProtos.Game.Builder, model.GameProtos.GameOrBuilder> 
          getGameFieldBuilder() {
        if (gameBuilder_ == null) {
          gameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              model.GameProtos.Game, model.GameProtos.Game.Builder, model.GameProtos.GameOrBuilder>(
                  getGame(),
                  getParentForChildren(),
                  isClean());
          game_ = null;
        }
        return gameBuilder_;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>optional string host = 2;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string host = 2;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            host_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 2;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000002);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional int32 port = 3;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 3;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.CreateGameResponse)
    }

    // @@protoc_insertion_point(class_scope:model.CreateGameResponse)
    private static final model.GameApiProtos.CreateGameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.GameApiProtos.CreateGameResponse();
    }

    public static model.GameApiProtos.CreateGameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CreateGameResponse>
        PARSER = new com.google.protobuf.AbstractParser<CreateGameResponse>() {
      public CreateGameResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CreateGameResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateGameResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateGameResponse> getParserForType() {
      return PARSER;
    }

    public model.GameApiProtos.CreateGameResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JoinGameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.JoinGameResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code model.JoinGameResponse}
   */
  public  static final class JoinGameResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.JoinGameResponse)
      JoinGameResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JoinGameResponse.newBuilder() to construct.
    private JoinGameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JoinGameResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JoinGameResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.GameApiProtos.internal_static_model_JoinGameResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.GameApiProtos.internal_static_model_JoinGameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.GameApiProtos.JoinGameResponse.class, model.GameApiProtos.JoinGameResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.GameApiProtos.JoinGameResponse)) {
        return super.equals(obj);
      }
      model.GameApiProtos.JoinGameResponse other = (model.GameApiProtos.JoinGameResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.GameApiProtos.JoinGameResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.JoinGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.JoinGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.JoinGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.GameApiProtos.JoinGameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.JoinGameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.JoinGameResponse)
        model.GameApiProtos.JoinGameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.GameApiProtos.internal_static_model_JoinGameResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.GameApiProtos.internal_static_model_JoinGameResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.GameApiProtos.JoinGameResponse.class, model.GameApiProtos.JoinGameResponse.Builder.class);
      }

      // Construct using model.GameApiProtos.JoinGameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.GameApiProtos.internal_static_model_JoinGameResponse_descriptor;
      }

      public model.GameApiProtos.JoinGameResponse getDefaultInstanceForType() {
        return model.GameApiProtos.JoinGameResponse.getDefaultInstance();
      }

      public model.GameApiProtos.JoinGameResponse build() {
        model.GameApiProtos.JoinGameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.GameApiProtos.JoinGameResponse buildPartial() {
        model.GameApiProtos.JoinGameResponse result = new model.GameApiProtos.JoinGameResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.GameApiProtos.JoinGameResponse) {
          return mergeFrom((model.GameApiProtos.JoinGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.GameApiProtos.JoinGameResponse other) {
        if (other == model.GameApiProtos.JoinGameResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.GameApiProtos.JoinGameResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.GameApiProtos.JoinGameResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.JoinGameResponse)
    }

    // @@protoc_insertion_point(class_scope:model.JoinGameResponse)
    private static final model.GameApiProtos.JoinGameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.GameApiProtos.JoinGameResponse();
    }

    public static model.GameApiProtos.JoinGameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JoinGameResponse>
        PARSER = new com.google.protobuf.AbstractParser<JoinGameResponse>() {
      public JoinGameResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new JoinGameResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JoinGameResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JoinGameResponse> getParserForType() {
      return PARSER;
    }

    public model.GameApiProtos.JoinGameResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LeaveGameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.LeaveGameResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code model.LeaveGameResponse}
   */
  public  static final class LeaveGameResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.LeaveGameResponse)
      LeaveGameResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LeaveGameResponse.newBuilder() to construct.
    private LeaveGameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LeaveGameResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LeaveGameResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.GameApiProtos.internal_static_model_LeaveGameResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.GameApiProtos.internal_static_model_LeaveGameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.GameApiProtos.LeaveGameResponse.class, model.GameApiProtos.LeaveGameResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.GameApiProtos.LeaveGameResponse)) {
        return super.equals(obj);
      }
      model.GameApiProtos.LeaveGameResponse other = (model.GameApiProtos.LeaveGameResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.LeaveGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.LeaveGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.LeaveGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.GameApiProtos.LeaveGameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.LeaveGameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.LeaveGameResponse)
        model.GameApiProtos.LeaveGameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.GameApiProtos.internal_static_model_LeaveGameResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.GameApiProtos.internal_static_model_LeaveGameResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.GameApiProtos.LeaveGameResponse.class, model.GameApiProtos.LeaveGameResponse.Builder.class);
      }

      // Construct using model.GameApiProtos.LeaveGameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.GameApiProtos.internal_static_model_LeaveGameResponse_descriptor;
      }

      public model.GameApiProtos.LeaveGameResponse getDefaultInstanceForType() {
        return model.GameApiProtos.LeaveGameResponse.getDefaultInstance();
      }

      public model.GameApiProtos.LeaveGameResponse build() {
        model.GameApiProtos.LeaveGameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.GameApiProtos.LeaveGameResponse buildPartial() {
        model.GameApiProtos.LeaveGameResponse result = new model.GameApiProtos.LeaveGameResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.GameApiProtos.LeaveGameResponse) {
          return mergeFrom((model.GameApiProtos.LeaveGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.GameApiProtos.LeaveGameResponse other) {
        if (other == model.GameApiProtos.LeaveGameResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.GameApiProtos.LeaveGameResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.GameApiProtos.LeaveGameResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.LeaveGameResponse)
    }

    // @@protoc_insertion_point(class_scope:model.LeaveGameResponse)
    private static final model.GameApiProtos.LeaveGameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.GameApiProtos.LeaveGameResponse();
    }

    public static model.GameApiProtos.LeaveGameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LeaveGameResponse>
        PARSER = new com.google.protobuf.AbstractParser<LeaveGameResponse>() {
      public LeaveGameResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LeaveGameResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LeaveGameResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeaveGameResponse> getParserForType() {
      return PARSER;
    }

    public model.GameApiProtos.LeaveGameResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetGameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.GetGameResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .model.Game game = 1;</code>
     */
    boolean hasGame();
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    model.GameProtos.Game getGame();
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    model.GameProtos.GameOrBuilder getGameOrBuilder();
  }
  /**
   * Protobuf type {@code model.GetGameResponse}
   */
  public  static final class GetGameResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.GetGameResponse)
      GetGameResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetGameResponse.newBuilder() to construct.
    private GetGameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetGameResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetGameResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              model.GameProtos.Game.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = game_.toBuilder();
              }
              game_ = input.readMessage(model.GameProtos.Game.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(game_);
                game_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.GameApiProtos.internal_static_model_GetGameResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.GameApiProtos.internal_static_model_GetGameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.GameApiProtos.GetGameResponse.class, model.GameApiProtos.GetGameResponse.Builder.class);
    }

    private int bitField0_;
    public static final int GAME_FIELD_NUMBER = 1;
    private model.GameProtos.Game game_;
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    public boolean hasGame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    public model.GameProtos.Game getGame() {
      return game_ == null ? model.GameProtos.Game.getDefaultInstance() : game_;
    }
    /**
     * <code>optional .model.Game game = 1;</code>
     */
    public model.GameProtos.GameOrBuilder getGameOrBuilder() {
      return game_ == null ? model.GameProtos.Game.getDefaultInstance() : game_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasGame()) {
        if (!getGame().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getGame());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGame());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.GameApiProtos.GetGameResponse)) {
        return super.equals(obj);
      }
      model.GameApiProtos.GetGameResponse other = (model.GameApiProtos.GetGameResponse) obj;

      boolean result = true;
      result = result && (hasGame() == other.hasGame());
      if (hasGame()) {
        result = result && getGame()
            .equals(other.getGame());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGame()) {
        hash = (37 * hash) + GAME_FIELD_NUMBER;
        hash = (53 * hash) + getGame().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.GameApiProtos.GetGameResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.GetGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.GetGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.GameApiProtos.GetGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.GameApiProtos.GetGameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.GetGameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.GetGameResponse)
        model.GameApiProtos.GetGameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.GameApiProtos.internal_static_model_GetGameResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.GameApiProtos.internal_static_model_GetGameResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.GameApiProtos.GetGameResponse.class, model.GameApiProtos.GetGameResponse.Builder.class);
      }

      // Construct using model.GameApiProtos.GetGameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGameFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (gameBuilder_ == null) {
          game_ = null;
        } else {
          gameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.GameApiProtos.internal_static_model_GetGameResponse_descriptor;
      }

      public model.GameApiProtos.GetGameResponse getDefaultInstanceForType() {
        return model.GameApiProtos.GetGameResponse.getDefaultInstance();
      }

      public model.GameApiProtos.GetGameResponse build() {
        model.GameApiProtos.GetGameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.GameApiProtos.GetGameResponse buildPartial() {
        model.GameApiProtos.GetGameResponse result = new model.GameApiProtos.GetGameResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (gameBuilder_ == null) {
          result.game_ = game_;
        } else {
          result.game_ = gameBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.GameApiProtos.GetGameResponse) {
          return mergeFrom((model.GameApiProtos.GetGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.GameApiProtos.GetGameResponse other) {
        if (other == model.GameApiProtos.GetGameResponse.getDefaultInstance()) return this;
        if (other.hasGame()) {
          mergeGame(other.getGame());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasGame()) {
          if (!getGame().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.GameApiProtos.GetGameResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.GameApiProtos.GetGameResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private model.GameProtos.Game game_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          model.GameProtos.Game, model.GameProtos.Game.Builder, model.GameProtos.GameOrBuilder> gameBuilder_;
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public boolean hasGame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public model.GameProtos.Game getGame() {
        if (gameBuilder_ == null) {
          return game_ == null ? model.GameProtos.Game.getDefaultInstance() : game_;
        } else {
          return gameBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder setGame(model.GameProtos.Game value) {
        if (gameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          game_ = value;
          onChanged();
        } else {
          gameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder setGame(
          model.GameProtos.Game.Builder builderForValue) {
        if (gameBuilder_ == null) {
          game_ = builderForValue.build();
          onChanged();
        } else {
          gameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder mergeGame(model.GameProtos.Game value) {
        if (gameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              game_ != null &&
              game_ != model.GameProtos.Game.getDefaultInstance()) {
            game_ =
              model.GameProtos.Game.newBuilder(game_).mergeFrom(value).buildPartial();
          } else {
            game_ = value;
          }
          onChanged();
        } else {
          gameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public Builder clearGame() {
        if (gameBuilder_ == null) {
          game_ = null;
          onChanged();
        } else {
          gameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public model.GameProtos.Game.Builder getGameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getGameFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      public model.GameProtos.GameOrBuilder getGameOrBuilder() {
        if (gameBuilder_ != null) {
          return gameBuilder_.getMessageOrBuilder();
        } else {
          return game_ == null ?
              model.GameProtos.Game.getDefaultInstance() : game_;
        }
      }
      /**
       * <code>optional .model.Game game = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          model.GameProtos.Game, model.GameProtos.Game.Builder, model.GameProtos.GameOrBuilder> 
          getGameFieldBuilder() {
        if (gameBuilder_ == null) {
          gameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              model.GameProtos.Game, model.GameProtos.Game.Builder, model.GameProtos.GameOrBuilder>(
                  getGame(),
                  getParentForChildren(),
                  isClean());
          game_ = null;
        }
        return gameBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.GetGameResponse)
    }

    // @@protoc_insertion_point(class_scope:model.GetGameResponse)
    private static final model.GameApiProtos.GetGameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.GameApiProtos.GetGameResponse();
    }

    public static model.GameApiProtos.GetGameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetGameResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetGameResponse>() {
      public GetGameResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetGameResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetGameResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetGameResponse> getParserForType() {
      return PARSER;
    }

    public model.GameApiProtos.GetGameResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_CreateGameResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_CreateGameResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_JoinGameResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_JoinGameResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_LeaveGameResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_LeaveGameResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_GetGameResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_GetGameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgameApi.proto\022\005model\032\ngame.proto\"K\n\022Cr" +
      "eateGameResponse\022\031\n\004game\030\001 \001(\0132\013.model.G" +
      "ame\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"\022\n\020JoinG" +
      "ameResponse\"\023\n\021LeaveGameResponse\",\n\017GetG" +
      "ameResponse\022\031\n\004game\030\001 \001(\0132\013.model.GameB\026" +
      "\n\005modelB\rGameApiProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          model.GameProtos.getDescriptor(),
        }, assigner);
    internal_static_model_CreateGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_CreateGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_CreateGameResponse_descriptor,
        new java.lang.String[] { "Game", "Host", "Port", });
    internal_static_model_JoinGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_JoinGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_JoinGameResponse_descriptor,
        new java.lang.String[] { });
    internal_static_model_LeaveGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_model_LeaveGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_LeaveGameResponse_descriptor,
        new java.lang.String[] { });
    internal_static_model_GetGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_model_GetGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_GetGameResponse_descriptor,
        new java.lang.String[] { "Game", });
    model.GameProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
