// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemApi.proto

package model;

public final class SystemApiProtos {
  private SystemApiProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetSystemInfosResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.GetSystemInfosResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    java.util.List<model.SystemInfoProtos.SystemInfo> 
        getSystemInfosList();
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    model.SystemInfoProtos.SystemInfo getSystemInfos(int index);
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    int getSystemInfosCount();
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    java.util.List<? extends model.SystemInfoProtos.SystemInfoOrBuilder> 
        getSystemInfosOrBuilderList();
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    model.SystemInfoProtos.SystemInfoOrBuilder getSystemInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.GetSystemInfosResponse}
   */
  public  static final class GetSystemInfosResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.GetSystemInfosResponse)
      GetSystemInfosResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetSystemInfosResponse.newBuilder() to construct.
    private GetSystemInfosResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSystemInfosResponse() {
      systemInfos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetSystemInfosResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                systemInfos_ = new java.util.ArrayList<model.SystemInfoProtos.SystemInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              systemInfos_.add(
                  input.readMessage(model.SystemInfoProtos.SystemInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          systemInfos_ = java.util.Collections.unmodifiableList(systemInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.SystemApiProtos.internal_static_model_GetSystemInfosResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.SystemApiProtos.internal_static_model_GetSystemInfosResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.SystemApiProtos.GetSystemInfosResponse.class, model.SystemApiProtos.GetSystemInfosResponse.Builder.class);
    }

    public static final int SYSTEMINFOS_FIELD_NUMBER = 1;
    private java.util.List<model.SystemInfoProtos.SystemInfo> systemInfos_;
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    public java.util.List<model.SystemInfoProtos.SystemInfo> getSystemInfosList() {
      return systemInfos_;
    }
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    public java.util.List<? extends model.SystemInfoProtos.SystemInfoOrBuilder> 
        getSystemInfosOrBuilderList() {
      return systemInfos_;
    }
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    public int getSystemInfosCount() {
      return systemInfos_.size();
    }
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    public model.SystemInfoProtos.SystemInfo getSystemInfos(int index) {
      return systemInfos_.get(index);
    }
    /**
     * <code>repeated .model.SystemInfo systemInfos = 1;</code>
     */
    public model.SystemInfoProtos.SystemInfoOrBuilder getSystemInfosOrBuilder(
        int index) {
      return systemInfos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSystemInfosCount(); i++) {
        if (!getSystemInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < systemInfos_.size(); i++) {
        output.writeMessage(1, systemInfos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < systemInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, systemInfos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.SystemApiProtos.GetSystemInfosResponse)) {
        return super.equals(obj);
      }
      model.SystemApiProtos.GetSystemInfosResponse other = (model.SystemApiProtos.GetSystemInfosResponse) obj;

      boolean result = true;
      result = result && getSystemInfosList()
          .equals(other.getSystemInfosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSystemInfosCount() > 0) {
        hash = (37 * hash) + SYSTEMINFOS_FIELD_NUMBER;
        hash = (53 * hash) + getSystemInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.SystemApiProtos.GetSystemInfosResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.SystemApiProtos.GetSystemInfosResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.GetSystemInfosResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.GetSystemInfosResponse)
        model.SystemApiProtos.GetSystemInfosResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.SystemApiProtos.internal_static_model_GetSystemInfosResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.SystemApiProtos.internal_static_model_GetSystemInfosResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.SystemApiProtos.GetSystemInfosResponse.class, model.SystemApiProtos.GetSystemInfosResponse.Builder.class);
      }

      // Construct using model.SystemApiProtos.GetSystemInfosResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSystemInfosFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (systemInfosBuilder_ == null) {
          systemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          systemInfosBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.SystemApiProtos.internal_static_model_GetSystemInfosResponse_descriptor;
      }

      public model.SystemApiProtos.GetSystemInfosResponse getDefaultInstanceForType() {
        return model.SystemApiProtos.GetSystemInfosResponse.getDefaultInstance();
      }

      public model.SystemApiProtos.GetSystemInfosResponse build() {
        model.SystemApiProtos.GetSystemInfosResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.SystemApiProtos.GetSystemInfosResponse buildPartial() {
        model.SystemApiProtos.GetSystemInfosResponse result = new model.SystemApiProtos.GetSystemInfosResponse(this);
        int from_bitField0_ = bitField0_;
        if (systemInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            systemInfos_ = java.util.Collections.unmodifiableList(systemInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.systemInfos_ = systemInfos_;
        } else {
          result.systemInfos_ = systemInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.SystemApiProtos.GetSystemInfosResponse) {
          return mergeFrom((model.SystemApiProtos.GetSystemInfosResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.SystemApiProtos.GetSystemInfosResponse other) {
        if (other == model.SystemApiProtos.GetSystemInfosResponse.getDefaultInstance()) return this;
        if (systemInfosBuilder_ == null) {
          if (!other.systemInfos_.isEmpty()) {
            if (systemInfos_.isEmpty()) {
              systemInfos_ = other.systemInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSystemInfosIsMutable();
              systemInfos_.addAll(other.systemInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.systemInfos_.isEmpty()) {
            if (systemInfosBuilder_.isEmpty()) {
              systemInfosBuilder_.dispose();
              systemInfosBuilder_ = null;
              systemInfos_ = other.systemInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              systemInfosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSystemInfosFieldBuilder() : null;
            } else {
              systemInfosBuilder_.addAllMessages(other.systemInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSystemInfosCount(); i++) {
          if (!getSystemInfos(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.SystemApiProtos.GetSystemInfosResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.SystemApiProtos.GetSystemInfosResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<model.SystemInfoProtos.SystemInfo> systemInfos_ =
        java.util.Collections.emptyList();
      private void ensureSystemInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          systemInfos_ = new java.util.ArrayList<model.SystemInfoProtos.SystemInfo>(systemInfos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          model.SystemInfoProtos.SystemInfo, model.SystemInfoProtos.SystemInfo.Builder, model.SystemInfoProtos.SystemInfoOrBuilder> systemInfosBuilder_;

      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public java.util.List<model.SystemInfoProtos.SystemInfo> getSystemInfosList() {
        if (systemInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(systemInfos_);
        } else {
          return systemInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public int getSystemInfosCount() {
        if (systemInfosBuilder_ == null) {
          return systemInfos_.size();
        } else {
          return systemInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public model.SystemInfoProtos.SystemInfo getSystemInfos(int index) {
        if (systemInfosBuilder_ == null) {
          return systemInfos_.get(index);
        } else {
          return systemInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder setSystemInfos(
          int index, model.SystemInfoProtos.SystemInfo value) {
        if (systemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemInfosIsMutable();
          systemInfos_.set(index, value);
          onChanged();
        } else {
          systemInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder setSystemInfos(
          int index, model.SystemInfoProtos.SystemInfo.Builder builderForValue) {
        if (systemInfosBuilder_ == null) {
          ensureSystemInfosIsMutable();
          systemInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          systemInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder addSystemInfos(model.SystemInfoProtos.SystemInfo value) {
        if (systemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemInfosIsMutable();
          systemInfos_.add(value);
          onChanged();
        } else {
          systemInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder addSystemInfos(
          int index, model.SystemInfoProtos.SystemInfo value) {
        if (systemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemInfosIsMutable();
          systemInfos_.add(index, value);
          onChanged();
        } else {
          systemInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder addSystemInfos(
          model.SystemInfoProtos.SystemInfo.Builder builderForValue) {
        if (systemInfosBuilder_ == null) {
          ensureSystemInfosIsMutable();
          systemInfos_.add(builderForValue.build());
          onChanged();
        } else {
          systemInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder addSystemInfos(
          int index, model.SystemInfoProtos.SystemInfo.Builder builderForValue) {
        if (systemInfosBuilder_ == null) {
          ensureSystemInfosIsMutable();
          systemInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          systemInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder addAllSystemInfos(
          java.lang.Iterable<? extends model.SystemInfoProtos.SystemInfo> values) {
        if (systemInfosBuilder_ == null) {
          ensureSystemInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, systemInfos_);
          onChanged();
        } else {
          systemInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder clearSystemInfos() {
        if (systemInfosBuilder_ == null) {
          systemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          systemInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public Builder removeSystemInfos(int index) {
        if (systemInfosBuilder_ == null) {
          ensureSystemInfosIsMutable();
          systemInfos_.remove(index);
          onChanged();
        } else {
          systemInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public model.SystemInfoProtos.SystemInfo.Builder getSystemInfosBuilder(
          int index) {
        return getSystemInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public model.SystemInfoProtos.SystemInfoOrBuilder getSystemInfosOrBuilder(
          int index) {
        if (systemInfosBuilder_ == null) {
          return systemInfos_.get(index);  } else {
          return systemInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public java.util.List<? extends model.SystemInfoProtos.SystemInfoOrBuilder> 
           getSystemInfosOrBuilderList() {
        if (systemInfosBuilder_ != null) {
          return systemInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(systemInfos_);
        }
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public model.SystemInfoProtos.SystemInfo.Builder addSystemInfosBuilder() {
        return getSystemInfosFieldBuilder().addBuilder(
            model.SystemInfoProtos.SystemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public model.SystemInfoProtos.SystemInfo.Builder addSystemInfosBuilder(
          int index) {
        return getSystemInfosFieldBuilder().addBuilder(
            index, model.SystemInfoProtos.SystemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .model.SystemInfo systemInfos = 1;</code>
       */
      public java.util.List<model.SystemInfoProtos.SystemInfo.Builder> 
           getSystemInfosBuilderList() {
        return getSystemInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          model.SystemInfoProtos.SystemInfo, model.SystemInfoProtos.SystemInfo.Builder, model.SystemInfoProtos.SystemInfoOrBuilder> 
          getSystemInfosFieldBuilder() {
        if (systemInfosBuilder_ == null) {
          systemInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              model.SystemInfoProtos.SystemInfo, model.SystemInfoProtos.SystemInfo.Builder, model.SystemInfoProtos.SystemInfoOrBuilder>(
                  systemInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          systemInfos_ = null;
        }
        return systemInfosBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.GetSystemInfosResponse)
    }

    // @@protoc_insertion_point(class_scope:model.GetSystemInfosResponse)
    private static final model.SystemApiProtos.GetSystemInfosResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.SystemApiProtos.GetSystemInfosResponse();
    }

    public static model.SystemApiProtos.GetSystemInfosResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetSystemInfosResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetSystemInfosResponse>() {
      public GetSystemInfosResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetSystemInfosResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSystemInfosResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSystemInfosResponse> getParserForType() {
      return PARSER;
    }

    public model.SystemApiProtos.GetSystemInfosResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_GetSystemInfosResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_GetSystemInfosResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017systemApi.proto\022\005model\032\020systemInfo.pro" +
      "to\"@\n\026GetSystemInfosResponse\022&\n\013systemIn" +
      "fos\030\001 \003(\0132\021.model.SystemInfoB\030\n\005modelB\017S" +
      "ystemApiProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          model.SystemInfoProtos.getDescriptor(),
        }, assigner);
    internal_static_model_GetSystemInfosResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_GetSystemInfosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_GetSystemInfosResponse_descriptor,
        new java.lang.String[] { "SystemInfos", });
    model.SystemInfoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
