// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemInfo.proto

package model;

public final class SystemInfoProtos {
  private SystemInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SystemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.SystemInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>optional uint64 freeMemory = 2;</code>
     */
    boolean hasFreeMemory();
    /**
     * <code>optional uint64 freeMemory = 2;</code>
     */
    long getFreeMemory();

    /**
     * <code>optional uint64 totalMemory = 3;</code>
     */
    boolean hasTotalMemory();
    /**
     * <code>optional uint64 totalMemory = 3;</code>
     */
    long getTotalMemory();

    /**
     * <code>optional uint64 maxMemory = 4;</code>
     */
    boolean hasMaxMemory();
    /**
     * <code>optional uint64 maxMemory = 4;</code>
     */
    long getMaxMemory();

    /**
     * <code>optional float cpuUsage = 5;</code>
     */
    boolean hasCpuUsage();
    /**
     * <code>optional float cpuUsage = 5;</code>
     */
    float getCpuUsage();
  }
  /**
   * Protobuf type {@code model.SystemInfo}
   */
  public  static final class SystemInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.SystemInfo)
      SystemInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SystemInfo.newBuilder() to construct.
    private SystemInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SystemInfo() {
      timestamp_ = 0L;
      freeMemory_ = 0L;
      totalMemory_ = 0L;
      maxMemory_ = 0L;
      cpuUsage_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SystemInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              freeMemory_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              totalMemory_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              maxMemory_ = input.readUInt64();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              cpuUsage_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.SystemInfoProtos.internal_static_model_SystemInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.SystemInfoProtos.internal_static_model_SystemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.SystemInfoProtos.SystemInfo.class, model.SystemInfoProtos.SystemInfo.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int FREEMEMORY_FIELD_NUMBER = 2;
    private long freeMemory_;
    /**
     * <code>optional uint64 freeMemory = 2;</code>
     */
    public boolean hasFreeMemory() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 freeMemory = 2;</code>
     */
    public long getFreeMemory() {
      return freeMemory_;
    }

    public static final int TOTALMEMORY_FIELD_NUMBER = 3;
    private long totalMemory_;
    /**
     * <code>optional uint64 totalMemory = 3;</code>
     */
    public boolean hasTotalMemory() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 totalMemory = 3;</code>
     */
    public long getTotalMemory() {
      return totalMemory_;
    }

    public static final int MAXMEMORY_FIELD_NUMBER = 4;
    private long maxMemory_;
    /**
     * <code>optional uint64 maxMemory = 4;</code>
     */
    public boolean hasMaxMemory() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 maxMemory = 4;</code>
     */
    public long getMaxMemory() {
      return maxMemory_;
    }

    public static final int CPUUSAGE_FIELD_NUMBER = 5;
    private float cpuUsage_;
    /**
     * <code>optional float cpuUsage = 5;</code>
     */
    public boolean hasCpuUsage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float cpuUsage = 5;</code>
     */
    public float getCpuUsage() {
      return cpuUsage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, freeMemory_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, totalMemory_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, maxMemory_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, cpuUsage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, freeMemory_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, totalMemory_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, maxMemory_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, cpuUsage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.SystemInfoProtos.SystemInfo)) {
        return super.equals(obj);
      }
      model.SystemInfoProtos.SystemInfo other = (model.SystemInfoProtos.SystemInfo) obj;

      boolean result = true;
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasFreeMemory() == other.hasFreeMemory());
      if (hasFreeMemory()) {
        result = result && (getFreeMemory()
            == other.getFreeMemory());
      }
      result = result && (hasTotalMemory() == other.hasTotalMemory());
      if (hasTotalMemory()) {
        result = result && (getTotalMemory()
            == other.getTotalMemory());
      }
      result = result && (hasMaxMemory() == other.hasMaxMemory());
      if (hasMaxMemory()) {
        result = result && (getMaxMemory()
            == other.getMaxMemory());
      }
      result = result && (hasCpuUsage() == other.hasCpuUsage());
      if (hasCpuUsage()) {
        result = result && (
            java.lang.Float.floatToIntBits(getCpuUsage())
            == java.lang.Float.floatToIntBits(
                other.getCpuUsage()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasFreeMemory()) {
        hash = (37 * hash) + FREEMEMORY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFreeMemory());
      }
      if (hasTotalMemory()) {
        hash = (37 * hash) + TOTALMEMORY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTotalMemory());
      }
      if (hasMaxMemory()) {
        hash = (37 * hash) + MAXMEMORY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMaxMemory());
      }
      if (hasCpuUsage()) {
        hash = (37 * hash) + CPUUSAGE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getCpuUsage());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.SystemInfoProtos.SystemInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.SystemInfoProtos.SystemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.SystemInfoProtos.SystemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.SystemInfoProtos.SystemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.SystemInfoProtos.SystemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.SystemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.SystemInfo)
        model.SystemInfoProtos.SystemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.SystemInfoProtos.internal_static_model_SystemInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.SystemInfoProtos.internal_static_model_SystemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.SystemInfoProtos.SystemInfo.class, model.SystemInfoProtos.SystemInfo.Builder.class);
      }

      // Construct using model.SystemInfoProtos.SystemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        freeMemory_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        totalMemory_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxMemory_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        cpuUsage_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.SystemInfoProtos.internal_static_model_SystemInfo_descriptor;
      }

      public model.SystemInfoProtos.SystemInfo getDefaultInstanceForType() {
        return model.SystemInfoProtos.SystemInfo.getDefaultInstance();
      }

      public model.SystemInfoProtos.SystemInfo build() {
        model.SystemInfoProtos.SystemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.SystemInfoProtos.SystemInfo buildPartial() {
        model.SystemInfoProtos.SystemInfo result = new model.SystemInfoProtos.SystemInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.freeMemory_ = freeMemory_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.totalMemory_ = totalMemory_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxMemory_ = maxMemory_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cpuUsage_ = cpuUsage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.SystemInfoProtos.SystemInfo) {
          return mergeFrom((model.SystemInfoProtos.SystemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.SystemInfoProtos.SystemInfo other) {
        if (other == model.SystemInfoProtos.SystemInfo.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasFreeMemory()) {
          setFreeMemory(other.getFreeMemory());
        }
        if (other.hasTotalMemory()) {
          setTotalMemory(other.getTotalMemory());
        }
        if (other.hasMaxMemory()) {
          setMaxMemory(other.getMaxMemory());
        }
        if (other.hasCpuUsage()) {
          setCpuUsage(other.getCpuUsage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.SystemInfoProtos.SystemInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.SystemInfoProtos.SystemInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long freeMemory_ ;
      /**
       * <code>optional uint64 freeMemory = 2;</code>
       */
      public boolean hasFreeMemory() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 freeMemory = 2;</code>
       */
      public long getFreeMemory() {
        return freeMemory_;
      }
      /**
       * <code>optional uint64 freeMemory = 2;</code>
       */
      public Builder setFreeMemory(long value) {
        bitField0_ |= 0x00000002;
        freeMemory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 freeMemory = 2;</code>
       */
      public Builder clearFreeMemory() {
        bitField0_ = (bitField0_ & ~0x00000002);
        freeMemory_ = 0L;
        onChanged();
        return this;
      }

      private long totalMemory_ ;
      /**
       * <code>optional uint64 totalMemory = 3;</code>
       */
      public boolean hasTotalMemory() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 totalMemory = 3;</code>
       */
      public long getTotalMemory() {
        return totalMemory_;
      }
      /**
       * <code>optional uint64 totalMemory = 3;</code>
       */
      public Builder setTotalMemory(long value) {
        bitField0_ |= 0x00000004;
        totalMemory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 totalMemory = 3;</code>
       */
      public Builder clearTotalMemory() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalMemory_ = 0L;
        onChanged();
        return this;
      }

      private long maxMemory_ ;
      /**
       * <code>optional uint64 maxMemory = 4;</code>
       */
      public boolean hasMaxMemory() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 maxMemory = 4;</code>
       */
      public long getMaxMemory() {
        return maxMemory_;
      }
      /**
       * <code>optional uint64 maxMemory = 4;</code>
       */
      public Builder setMaxMemory(long value) {
        bitField0_ |= 0x00000008;
        maxMemory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 maxMemory = 4;</code>
       */
      public Builder clearMaxMemory() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxMemory_ = 0L;
        onChanged();
        return this;
      }

      private float cpuUsage_ ;
      /**
       * <code>optional float cpuUsage = 5;</code>
       */
      public boolean hasCpuUsage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float cpuUsage = 5;</code>
       */
      public float getCpuUsage() {
        return cpuUsage_;
      }
      /**
       * <code>optional float cpuUsage = 5;</code>
       */
      public Builder setCpuUsage(float value) {
        bitField0_ |= 0x00000010;
        cpuUsage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float cpuUsage = 5;</code>
       */
      public Builder clearCpuUsage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cpuUsage_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.SystemInfo)
    }

    // @@protoc_insertion_point(class_scope:model.SystemInfo)
    private static final model.SystemInfoProtos.SystemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.SystemInfoProtos.SystemInfo();
    }

    public static model.SystemInfoProtos.SystemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SystemInfo>
        PARSER = new com.google.protobuf.AbstractParser<SystemInfo>() {
      public SystemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SystemInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SystemInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SystemInfo> getParserForType() {
      return PARSER;
    }

    public model.SystemInfoProtos.SystemInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_SystemInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_SystemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020systemInfo.proto\022\005model\"m\n\nSystemInfo\022" +
      "\021\n\ttimestamp\030\001 \002(\004\022\022\n\nfreeMemory\030\002 \001(\004\022\023" +
      "\n\013totalMemory\030\003 \001(\004\022\021\n\tmaxMemory\030\004 \001(\004\022\020" +
      "\n\010cpuUsage\030\005 \001(\002B\031\n\005modelB\020SystemInfoPro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_SystemInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_SystemInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_SystemInfo_descriptor,
        new java.lang.String[] { "Timestamp", "FreeMemory", "TotalMemory", "MaxMemory", "CpuUsage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
